--- #YAML:1.0
name:                HTTP-Cookies-Mozilla
version:             1.11
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    HTTP::Cookies:                 1.25
    Test::More:                    0
    Text::Diff:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - brian d foy <bdfoy@cpan.org>
